version: '3.7'

services:
  database_mybooks:
    image: postgres
    container_name: database_mybooks
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=mybooks
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: mybooks
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database_mybooks
    depends_on:
      - database_mybooks

volumes:
  pgdata:
    driver: local